// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAClTA4bUxiH-GBQ51i0Ro0xzJu_HvR3K8',
    appId: '1:298355899069:web:9c98187bfb5b0be21b55d4',
    messagingSenderId: '298355899069',
    projectId: 'bugreportapp-a2fe2',
    authDomain: 'bugreportapp-a2fe2.firebaseapp.com',
    storageBucket: 'bugreportapp-a2fe2.appspot.com',
    measurementId: 'G-N1QRFQBD92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qNAstljHEruPh4fqWicCw7ttpyeGnuU',
    appId: '1:298355899069:android:a14dfa9b9f76ca661b55d4',
    messagingSenderId: '298355899069',
    projectId: 'bugreportapp-a2fe2',
    storageBucket: 'bugreportapp-a2fe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTBZe17GTBh8T8P6ru3Ybdhrbqi_8t1_4',
    appId: '1:298355899069:ios:dd5e998b7dafbd291b55d4',
    messagingSenderId: '298355899069',
    projectId: 'bugreportapp-a2fe2',
    storageBucket: 'bugreportapp-a2fe2.appspot.com',
    iosClientId: '298355899069-rht91d8cfknmsaj335rsgqo5j6livsda.apps.googleusercontent.com',
    iosBundleId: 'com.example.bugReport',
  );
}
